### ISSUE TITLE
Logowanie uzytkownikow

### ISSUE THREAD

**Issue by swpw5** [swpw5/mboard#1]
wydaje mi sie ze mozna to obsluzyc w sql
po logowaniu odpalała by się tablica(e)

**Comment by ZimaKamil** [comment]
Proponuję sprawdzić działanie https://github.com/DotNet4Neo4j/Neo4j.AspNet.Identity
Nie trzeba byłoby mieszać baz

**Comment by pnowk** [comment]
ok
