### ISSUE TITLE
szkielet aplikacji

### ISSUE THREAD

**Issue by swpw5** [swpw5/mboard#2]
model danych, dbcontext, layout / menu glowne, home controller

**Comment by ZimaKamil** [comment]
Layout w trakcie realizacji, wstępny szkic modelu:
![mboarddb](https://user-images.githubusercontent.com/28480746/32912474-7351d3e4-cb0f-11e7-9f0d-1939a3a97215.png)
![mboarddbmodel](https://user-images.githubusercontent.com/28480746/32912475-736f688c-cb0f-11e7-8202-d6ffcb10666b.png)

![classdiagram](https://user-images.githubusercontent.com/28480746/32914076-9ae1ac5e-cb14-11e7-870c-a9c204d103d8.png)
